CREATE USER ro_user WITH PASSWORD 'ro_user';

GRANT CONNECT ON DATABASE customdatabase TO ro_user;

GRANT USAGE ON SCHEMA public TO ro_user;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ro_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ro_user;
